### ISSUE TITLE
Still getting gun bugs - comb. of sprite, range, speed and damage. (and still seeing speeding players)

### ISSUE THREAD

**Issue by ghost** [BitfoxCanada/bruh-io-bug-tracker#10]
<img width="799" alt="screen shot 2018-01-12 at 21 03 28" src="https://user-images.githubusercontent.com/35238821/34893182-6a9b9e7a-f7dc-11e7-897a-94176b93d32b.png">

**Comment by asdad-github** [comment]
Second game and a new version, hard to show. Sprite is submachine-gun. Fire-rate is sniper BUT damage is what I guess is one bullet from submachine-gun.

<img width="586" alt="screen shot 2018-01-12 at 21 08 28" src="https://user-images.githubusercontent.com/35238821/34893311-ea9a0d6e-f7dc-11e7-83b9-0b1404982d48.png">

**Comment by asdad-github** [comment]
Getting many different combinations now. Fx getting the range of snipe with speed of small submachine-gun.

**Comment by asdad-github** [comment]
<img width="699" alt="screen shot 2018-01-12 at 23 59 16" src="https://user-images.githubusercontent.com/35238821/34898813-4eabd2f2-f7f5-11e7-81af-27d05decea7f.png">

**Comment by Samstiles** [comment]
Thanks for the bug report! This is a duplicate of #2 (they're all the same bug in the engine, a part of the engine called the interpolator), so I'm going to close this issue. Feel free to follow progress on bug #2 if you're curious.

**Comment by Samstiles** [comment]
This is fixed now!
