### ISSUE TITLE
Death screen needs a close button

### ISSUE THREAD

**Issue by DoctorKill** [BitfoxCanada/bruh-io-bug-tracker#16]
After a match is finished, ads wont disappear and it also  logs me out...I do not experience any lags as some previews reported issues, but those issues that i state above, are really annoying.
![bruh](https://user-images.githubusercontent.com/36680510/36453543-aa40d2cc-1698-11e8-8816-f26efa8ce90e.png)

**Comment by TauClops** [comment]
Why don't you just press "Spectate"?
![image](https://user-images.githubusercontent.com/36796814/36632673-2210a17c-1957-11e8-869e-9dd47520b3b2.png)

**Comment by Samstiles** [comment]
The death screen how has a close button - closing this issue
