### ISSUE TITLE
Skins not working

### ISSUE THREAD

**Issue by worthywaffles** [BitfoxCanada/bruh-io-bug-tracker#17]
I have gotten 25 wins and whenever I click on a skin to use it, it won't load it into the game.

**Comment by king21savage** [comment]
yeah bruh.io creaters please fix that i have 103 wins and cant get skins

**Comment by LavarBal** [comment]
I have over 250 wins and my skin won't load into the game.

**Comment by Samstiles** [comment]
thanks you guys, im investigating this today

**Comment by Samstiles** [comment]
This is fixed now!
