### ISSUE TITLE
Bandage Not Working

### ISSUE THREAD

**Issue by atreydesai** [BitfoxCanada/bruh-io-bug-tracker#18]
Bandages often do not show up when they are picked up. They still can be used though but do not show up in 6 squares on the bottom-right.

**Comment by Samstiles** [comment]
Thanks for the bug report @atreydesai - this is actually the same bug as bug #2 (it's a bug in our engine). I'm going to close this bug for now so we track the progress in one place (#2).

**Comment by Samstiles** [comment]
This is fixed now!
