### ISSUE TITLE
Alive Ghost / Healthbar bug / Weapon visual bug / More

### ISSUE THREAD

**Issue by saifalfalah** [BitfoxCanada/bruh-io-bug-tracker#2]
You die and your ghost still has some life left.

And then, sometimes when a new game starts, you're still ghost.

**Comment by Samstiles** [comment]
Thanks for the bug report! This is a known issue that can happen as a result of what's known as our `interpolator bug`. I'll spare you the details, but we are aware of the issue and have a fix in the works.

**Comment by Samstiles** [comment]
This is fixed now!

**Comment by Samstiles** [comment]
This is fixed now!
