### ISSUE TITLE
weapons bugs

### ISSUE THREAD

**Issue by Twisterman** [BitfoxCanada/bruh-io-bug-tracker#24]
Sometimes when weapons are pick up, work with characteristics of other weapons, for example: an AK firing like a sniper but without so much range, or an M16 like a shotgun. And to make it work as they should, you have to drop it and pick it up again.

**Comment by Samstiles** [comment]
Hey @Twisterman thanks for the bug report. This is a known issue - it comes from something called our "interp bug". I'll leave this issue open until we resolve it.

**Comment by Samstiles** [comment]
This is fixed now!
