### ISSUE TITLE
Gadgets bugs

### ISSUE THREAD

**Issue by Twisterman** [BitfoxCanada/bruh-io-bug-tracker#25]
The laser, bandages and analgesics can sometimes not be collected, or if they are collected they are not saw in inventory.

**Comment by Samstiles** [comment]
Hey @Twisterman  thanks for the bug report. This is a known issue - it comes from something called our "interp bug". I'll leave this issue open until we resolve it.

**Comment by Samstiles** [comment]
This is fixed now!
