### ISSUE TITLE
Screen spectator mode during match

### ISSUE THREAD

**Issue by Twisterman** [BitfoxCanada/bruh-io-bug-tracker#26]
Sometimes even though you have been playing in the same match for a while, when the game is over and you start again, the screen has the appearance of "spectator" because you play and you do not see the gadgets you collect, nor the health, nor the ammunition.

**Comment by Samstiles** [comment]
Hey @Twisterman  thanks for the bug report. This is a known issue - it comes from something called our "interp bug". I'll leave this issue open until we resolve it.

**Comment by Samstiles** [comment]
This is fixed now!
