### ISSUE TITLE
Loot - ammo count - fire rate - log in bug

### ISSUE THREAD

**Issue by GoboC** [BitfoxCanada/bruh-io-bug-tracker#28]
I have a few bugs to report. One of them is probably very common and it's when you can't pick up your loot. The next is when you pick up the loot, and you have the same fire rate, and ammo count as the weapon you had before. For example, you had an ak47, and you picked up a bmg. It takes the damage of the bmg, but keeps the ammo count, and fire rate of the ak47. So it would be an overpowered auto sniper. Also if you log in, sometimes your name won't pop up

**Comment by Samstiles** [comment]
Hey @GoboC thanks for the bug report. All of these are known issues - they come from something called our "interp bug". I'll leave this issue open until we resolve it.

**Comment by Samstiles** [comment]
This is fixed now!
