### ISSUE TITLE
Map Glitches

### ISSUE THREAD

**Issue by ag4sh** [BitfoxCanada/bruh-io-bug-tracker#29]
A few map glitches I spotted.

![screenshot from 2018-02-26 10 37 40](https://user-images.githubusercontent.com/36843303/36664064-d6194b96-1ae3-11e8-8c6c-17a68ec33a57.png)
![screenshot from 2018-02-26 10 38 01](https://user-images.githubusercontent.com/36843303/36664065-d6321072-1ae3-11e8-8fd0-06935b2ced8f.png)
![screenshot from 2018-02-26 10 38 08](https://user-images.githubusercontent.com/36843303/36664066-d64aabaa-1ae3-11e8-9475-fa968b499815.png)
![screenshot from 2018-02-26 10 39 27](https://user-images.githubusercontent.com/36843303/36664067-d6636dca-1ae3-11e8-86a7-d8b23f541c8a.png)
![screenshot from 2018-02-26 10 43 35](https://user-images.githubusercontent.com/36843303/36664068-d67b86b2-1ae3-11e8-8b61-75d43c9a1d03.png)

**Comment by ag4sh** [comment]
a few more
![screenshot from 2018-02-26 11 16 24](https://user-images.githubusercontent.com/36843303/36665858-fc8e03de-1ae8-11e8-98ec-7560c03ea2f7.png)
![screenshot from 2018-02-26 11 16 27](https://user-images.githubusercontent.com/36843303/36665859-fcadda2e-1ae8-11e8-94f1-0d9f9a8f24cc.png)
![screenshot from 2018-02-26 11 17 32](https://user-images.githubusercontent.com/36843303/36665860-fcc92770-1ae8-11e8-9e61-57a721fdcd0b.png)
![screenshot from 2018-02-26 11 17 42](https://user-images.githubusercontent.com/36843303/36665861-fce2bf50-1ae8-11e8-94ea-1efbedb55999.png)
![screenshot from 2018-02-26 11 17 55](https://user-images.githubusercontent.com/36843303/36665862-fd008c56-1ae8-11e8-90b2-314ad8f303e4.png)
![screenshot from 2018-02-26 11 22 26](https://user-images.githubusercontent.com/36843303/36665863-fd1a7f30-1ae8-11e8-80d7-ddfe18ede7d9.png)

**Comment by Samstiles** [comment]
Fixing these tonight
