### ISSUE TITLE
Minimap: Small white circles

### ISSUE THREAD

**Issue by ghost** [BitfoxCanada/bruh-io-bug-tracker#3]
<img width="104" alt="screen shot 2018-01-08 at 21 19 44" src="https://user-images.githubusercontent.com/35238821/34692118-4a7bde18-f4bf-11e7-8f6a-0de4ddee7278.png">
<img width="105" alt="screen shot 2018-01-08 at 21 19 50" src="https://user-images.githubusercontent.com/35238821/34692119-4a997e32-f4bf-11e7-9404-9d2077880fd6.png">
<img width="105" alt="screen shot 2018-01-08 at 21 34 50" src="https://user-images.githubusercontent.com/35238821/34692130-4fce2376-f4bf-11e7-87dd-5b643b762ed5.png">
<img width="103" alt="screen shot 2018-01-08 at 21 35 18" src="https://user-images.githubusercontent.com/35238821/34692131-4fe93f4e-f4bf-11e7-9d48-e6b350bd8d4d.png">

**Comment by Samstiles** [comment]
Closing this issue as it's no longer relevant w/ the square :)
