### ISSUE TITLE
Account not tracking wins

### ISSUE THREAD

**Issue by Subwaycup** [BitfoxCanada/bruh-io-bug-tracker#31]
When I go to 'My Account', it shows spaces for amount of wins. I have won about 6 matches but it shows that I have not won any matches at all.

**Comment by ag4sh** [comment]
I have the same problem
![leaderboard](https://user-images.githubusercontent.com/36843303/36838578-db1e813e-1d3f-11e8-89c3-1252823e1b02.png)

**Comment by PearMoon** [comment]
My account wins and details are not being track and because there not being tracked i'm unable to obtain any skins.

**Comment by Samstiles** [comment]
This is fixed now!
