### ISSUE TITLE
Username incorrect - Patch 2.0

### ISSUE THREAD

**Issue by chazzels** [BitfoxCanada/bruh-io-bug-tracker#37]
Opened my browser (Chrome v64.0.3282.186) to play some Bruh.io. I was already logged on like I usually am. But once I got in a game the username was not mine. Others in chat also saw this username that was not mine. upon exiting to the menu and hard refreshing my username is now correct. 

I did not post my username or other accounts username on purpose. I am apart of your of your discord server and would be happy to connect with one of the dev/admins there to rely that information. 

If need let me know who I should contact on the server and when and I will gladly provide the info to them.

**Comment by Samstiles** [comment]
This is fixed now!
