### ISSUE TITLE
Map - Terrain - Player collision: Another trap

### ISSUE THREAD

**Issue by ghost** [BitfoxCanada/bruh-io-bug-tracker#4]
People think they can get through while trying to escape hail of bullets. 
Witnessed a dozen times. 

<img width="398" alt="its a trap" src="https://user-images.githubusercontent.com/35238821/34692242-c74e9f02-f4bf-11e7-944e-61726277d3ce.png">

**Comment by Samstiles** [comment]
Thanks for the bug report! Closing this issue for now as there's a new map (and new versions of this problem to find!)
