### ISSUE TITLE
Items glitching

### ISSUE THREAD

**Issue by worthywaffles** [BitfoxCanada/bruh-io-bug-tracker#40]
You will get and item (occurs most often with meds) and the next round you will start with it in your inventory and not be able to pick up or use them. Same thing with the red dot sight. Other times you will pick up an item and it simply won't register give the item to you or it won't work when picked up (meds and red dot sight). Haven't had the problem with sights just meds and red dot sight

**Comment by Samstiles** [comment]
This is fixed now!
