### ISSUE TITLE
i dont know how to qualify this bug

### ISSUE THREAD

**Issue by GUA3D** [BitfoxCanada/bruh-io-bug-tracker#42]
I was waiting for players on the server "New York A" and I started a game with another player. I had a kevlar vest, a medpack, painkillers and a BMG. after winning the game, the other player left and I was waiting for another player but I noticed that I had kept all my equipment and even if I had the basic weapon, I could shoot only two balls, like the BMG. In this part I could not get bandages and I could recover medpack and painkillers to infinity. I still won this game and I started another one with the same player and I noticed the same bugs and another: I could recover all the healing objects to infinity but their name was not displayed . I lost this part and I left to report these bugs. (sorry for google translate)

**Comment by Samstiles** [comment]
This is fixed now!
