### ISSUE TITLE
ghost bug

### ISSUE THREAD

**Issue by Gnar432626** [BitfoxCanada/bruh-io-bug-tracker#5]
i just had that bug
and 
![capture](https://user-images.githubusercontent.com/35105666/34720241-fb1bb8a0-f50b-11e7-9c95-60d719ccfd32.PNG)

  i was alive and working and i don't think people saw me as that because when i went up to them they just did nothing

**Comment by Samstiles** [comment]
Thanks for the bug report! This is a duplicate of bug #2 so I'm going to close it for now :)
