### ISSUE TITLE
UI: Placement of health and "gas is coming"

### ISSUE THREAD

**Issue by ghost** [BitfoxCanada/bruh-io-bug-tracker#8]
Change:
Placement of UI elements so they don't block aiming close to edge of screen. 

Why:
In normal play you get an advantage attacking from below, because top of screen has less interference. You see the person your attacking earlier then the victim, who as an added bonus will have a difficult time getting good aim. 

Really bad when your running down the screen, away from the gas and get the "gas is coming" on top of health, in the way of your angle of attack. 

Possible issue:
As of now it pretty much leaves the corners. Unless the way the information is shown changes. Symbols, maybe moving etc. etc. etc.

**Comment by Samstiles** [comment]
Thanks for the bug report! The UI has changed significantly, if this is still an issue, could you take some screenshots and submit a new bug report?
