### ISSUE TITLE
Discord: SpongeLords hall of fame would be nice :)

### ISSUE THREAD

**Issue by ghost** [BitfoxCanada/bruh-io-bug-tracker#9]
SpongeLord - Today at 6:59 PM
@sam would be nice to leave all players that reached all-time #1 in the Discord rol, sort of NBA's hall of fame but for shorter ppl
👏1

asdad - Today at 7:00 PM
Second that. Like a gallery of washed up former glory.

**Comment by Samstiles** [comment]
Thanks for the bug report! Closing this for now as it's a feature request. I've added it to our feature backlog.
